### ISSUE TITLE
would it be possible to control the order of controls?

### ISSUE THREAD

**Issue by pbiecek** [monikachudek/shimex#9]
for titanic dataset, I would like to have selectInput for country and then for gender (now it's alfabetical)

**Comment by monikachudek** [comment]
There has been created new parameter `input order` that enables ordering of displayed input.

**Comment by monikachudek** [comment]
@pbiecek,

I am working on the solution that we discussed (using renderUI). And there is a question - 
What values should be used for variables that are not displayed in the input list?
So far it has been the value of the first observation, which doesn't make much sense.
Whether an argument 'new_obs' should be required? Then the non-displayed variables would have the given values.

**Comment by pbiecek** [comment]
Yes, I think that the best option is to force use to set the `new_obs` argument,
then defaults will be extracted from this observation.

**Comment by monikachudek** [comment]
done

**Comment by pbiecek** [comment]
thanks, it's working
